# permissions for end users to edit customsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customsecret-editor-role
rules:
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customsecrets/status
  verbs:
  - get
