# permissions for end users to edit customconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customconfigmap-editor-role
rules:
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customconfigmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customconfigmaps/status
  verbs:
  - get
