# permissions for end users to view customsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customsecret-viewer-role
rules:
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customsecrets/status
  verbs:
  - get
