
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customconfigmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customconfigmaps/finalizers
  verbs:
  - update
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customconfigmaps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - configurator.gopaddle.io
  resources:
  - customsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
