/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/gopaddle-io/configurator/apis/configurator.gopaddle.io/v1alpha1"
	scheme "github.com/gopaddle-io/configurator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CustomSecretsGetter has a method to return a CustomSecretInterface.
// A group's client should implement this interface.
type CustomSecretsGetter interface {
	CustomSecrets(namespace string) CustomSecretInterface
}

// CustomSecretInterface has methods to work with CustomSecret resources.
type CustomSecretInterface interface {
	Create(ctx context.Context, customSecret *v1alpha1.CustomSecret, opts v1.CreateOptions) (*v1alpha1.CustomSecret, error)
	Update(ctx context.Context, customSecret *v1alpha1.CustomSecret, opts v1.UpdateOptions) (*v1alpha1.CustomSecret, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CustomSecret, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CustomSecretList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CustomSecret, err error)
	CustomSecretExpansion
}

// customSecrets implements CustomSecretInterface
type customSecrets struct {
	client rest.Interface
	ns     string
}

// newCustomSecrets returns a CustomSecrets
func newCustomSecrets(c *ConfiguratorV1alpha1Client, namespace string) *customSecrets {
	return &customSecrets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the customSecret, and returns the corresponding customSecret object, and an error if there is any.
func (c *customSecrets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CustomSecret, err error) {
	result = &v1alpha1.CustomSecret{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("customsecrets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CustomSecrets that match those selectors.
func (c *customSecrets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CustomSecretList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CustomSecretList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("customsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested customSecrets.
func (c *customSecrets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("customsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a customSecret and creates it.  Returns the server's representation of the customSecret, and an error, if there is any.
func (c *customSecrets) Create(ctx context.Context, customSecret *v1alpha1.CustomSecret, opts v1.CreateOptions) (result *v1alpha1.CustomSecret, err error) {
	result = &v1alpha1.CustomSecret{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("customsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(customSecret).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a customSecret and updates it. Returns the server's representation of the customSecret, and an error, if there is any.
func (c *customSecrets) Update(ctx context.Context, customSecret *v1alpha1.CustomSecret, opts v1.UpdateOptions) (result *v1alpha1.CustomSecret, err error) {
	result = &v1alpha1.CustomSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("customsecrets").
		Name(customSecret.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(customSecret).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the customSecret and deletes it. Returns an error if one occurs.
func (c *customSecrets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("customsecrets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *customSecrets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("customsecrets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched customSecret.
func (c *customSecrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CustomSecret, err error) {
	result = &v1alpha1.CustomSecret{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("customsecrets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
