{{- if .Values.deployments.admissionController }}
{{ $tls := fromYaml ( include "admission-controller.gen-certs" . ) }}
{{- if .Values.admissionSecret.create }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "admission-controller.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "configurator.chart" . }}
type: Opaque
data:
  cert.pem: {{ $tls.clientCert }}
  key.pem: {{ $tls.clientKey }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admission-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "configurator.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "admission-controller.name" . }} 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "admission-controller.name" . }}
    spec:
      containers:
      - image: "{{ .Values.admissionController.image.repository }}:{{ coalesce .Values.admissionController.image.tag .Chart.AppVersion }}"
        command:
        - ./controllerWebhook
        args:
        - -tlsCertFile=/etc/webhook/certs/cert.pem
        - -tlsKeyFile=/etc/webhook/certs/key.pem
        imagePullPolicy: Always
        name: controllerwebhook
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ template "admission-controller.secret.name" . }}
      serviceAccountName:  {{ .Release.Name }}-controller
      imagePullSecrets:
  {{- range .Values.admissionController.imagePullSecrets }}
      - name: "{{ . }}"
  {{- end }}

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "admission-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "configurator.chart" . }}
webhooks:
- name: deploycontroller.configurator.gopaddle.io
  clientConfig:
    service:
      name: {{ include "admission-controller.service.name" . }}
      namespace: {{ .Release.Namespace }}
      path: "/deploycontroller"
    caBundle: {{ $tls.caCert }}
  failurePolicy: Ignore
  rules:
  - operations: ["CREATE","UPDATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
- name: stscontroller.configurator.gopaddle.io
  clientConfig:
    service:
      name: {{ include "admission-controller.service.name" . }}
      namespace: {{ .Release.Namespace }}
      path: "/stscontroller"
    caBundle: {{ $tls.caCert }}
  failurePolicy: Ignore
  rules:
  - operations: ["CREATE","UPDATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["statefulsets"]
  admissionReviewVersions: ["v1"]
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "admission-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "configurator.chart" . }}
webhooks:
- name: podcontroller.configurator.gopaddle.io
  clientConfig:
    service:
      name: {{ include "admission-controller.service.name" . }}
      namespace: {{ .Release.Namespace }}
      path: "/podcontroller"
    caBundle: {{ $tls.caCert }}
  failurePolicy: Ignore
  rules:
  - operations: ["CREATE",UPDATE]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
{{- end}}