/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/gopaddle-io/configurator/apis/configurator.gopaddle.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomConfigMaps implements CustomConfigMapInterface
type FakeCustomConfigMaps struct {
	Fake *FakeConfiguratorV1alpha1
	ns   string
}

var customconfigmapsResource = schema.GroupVersionResource{Group: "configurator.gopaddle.io", Version: "v1alpha1", Resource: "customconfigmaps"}

var customconfigmapsKind = schema.GroupVersionKind{Group: "configurator.gopaddle.io", Version: "v1alpha1", Kind: "CustomConfigMap"}

// Get takes name of the customConfigMap, and returns the corresponding customConfigMap object, and an error if there is any.
func (c *FakeCustomConfigMaps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CustomConfigMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customconfigmapsResource, c.ns, name), &v1alpha1.CustomConfigMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomConfigMap), err
}

// List takes label and field selectors, and returns the list of CustomConfigMaps that match those selectors.
func (c *FakeCustomConfigMaps) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CustomConfigMapList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customconfigmapsResource, customconfigmapsKind, c.ns, opts), &v1alpha1.CustomConfigMapList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CustomConfigMapList{ListMeta: obj.(*v1alpha1.CustomConfigMapList).ListMeta}
	for _, item := range obj.(*v1alpha1.CustomConfigMapList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customConfigMaps.
func (c *FakeCustomConfigMaps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customconfigmapsResource, c.ns, opts))

}

// Create takes the representation of a customConfigMap and creates it.  Returns the server's representation of the customConfigMap, and an error, if there is any.
func (c *FakeCustomConfigMaps) Create(ctx context.Context, customConfigMap *v1alpha1.CustomConfigMap, opts v1.CreateOptions) (result *v1alpha1.CustomConfigMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customconfigmapsResource, c.ns, customConfigMap), &v1alpha1.CustomConfigMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomConfigMap), err
}

// Update takes the representation of a customConfigMap and updates it. Returns the server's representation of the customConfigMap, and an error, if there is any.
func (c *FakeCustomConfigMaps) Update(ctx context.Context, customConfigMap *v1alpha1.CustomConfigMap, opts v1.UpdateOptions) (result *v1alpha1.CustomConfigMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customconfigmapsResource, c.ns, customConfigMap), &v1alpha1.CustomConfigMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomConfigMap), err
}

// Delete takes name of the customConfigMap and deletes it. Returns an error if one occurs.
func (c *FakeCustomConfigMaps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(customconfigmapsResource, c.ns, name), &v1alpha1.CustomConfigMap{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomConfigMaps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customconfigmapsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CustomConfigMapList{})
	return err
}

// Patch applies the patch and returns the patched customConfigMap.
func (c *FakeCustomConfigMaps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CustomConfigMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customconfigmapsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CustomConfigMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomConfigMap), err
}
