/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/gopaddle-io/configurator/apis/configurator.gopaddle.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomSecrets implements CustomSecretInterface
type FakeCustomSecrets struct {
	Fake *FakeConfiguratorV1alpha1
	ns   string
}

var customsecretsResource = schema.GroupVersionResource{Group: "configurator.gopaddle.io", Version: "v1alpha1", Resource: "customsecrets"}

var customsecretsKind = schema.GroupVersionKind{Group: "configurator.gopaddle.io", Version: "v1alpha1", Kind: "CustomSecret"}

// Get takes name of the customSecret, and returns the corresponding customSecret object, and an error if there is any.
func (c *FakeCustomSecrets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CustomSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customsecretsResource, c.ns, name), &v1alpha1.CustomSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomSecret), err
}

// List takes label and field selectors, and returns the list of CustomSecrets that match those selectors.
func (c *FakeCustomSecrets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CustomSecretList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customsecretsResource, customsecretsKind, c.ns, opts), &v1alpha1.CustomSecretList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CustomSecretList{ListMeta: obj.(*v1alpha1.CustomSecretList).ListMeta}
	for _, item := range obj.(*v1alpha1.CustomSecretList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customSecrets.
func (c *FakeCustomSecrets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customsecretsResource, c.ns, opts))

}

// Create takes the representation of a customSecret and creates it.  Returns the server's representation of the customSecret, and an error, if there is any.
func (c *FakeCustomSecrets) Create(ctx context.Context, customSecret *v1alpha1.CustomSecret, opts v1.CreateOptions) (result *v1alpha1.CustomSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customsecretsResource, c.ns, customSecret), &v1alpha1.CustomSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomSecret), err
}

// Update takes the representation of a customSecret and updates it. Returns the server's representation of the customSecret, and an error, if there is any.
func (c *FakeCustomSecrets) Update(ctx context.Context, customSecret *v1alpha1.CustomSecret, opts v1.UpdateOptions) (result *v1alpha1.CustomSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customsecretsResource, c.ns, customSecret), &v1alpha1.CustomSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomSecret), err
}

// Delete takes name of the customSecret and deletes it. Returns an error if one occurs.
func (c *FakeCustomSecrets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(customsecretsResource, c.ns, name), &v1alpha1.CustomSecret{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomSecrets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customsecretsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CustomSecretList{})
	return err
}

// Patch applies the patch and returns the patched customSecret.
func (c *FakeCustomSecrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CustomSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customsecretsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CustomSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomSecret), err
}
