// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gopaddle-io/configurator/pkg/apis/configuratorcontroller/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CustomSecretLister helps list CustomSecrets.
// All objects returned here must be treated as read-only.
type CustomSecretLister interface {
	// List lists all CustomSecrets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.CustomSecret, err error)
	// CustomSecrets returns an object that can list and get CustomSecrets.
	CustomSecrets(namespace string) CustomSecretNamespaceLister
	CustomSecretListerExpansion
}

// customSecretLister implements the CustomSecretLister interface.
type customSecretLister struct {
	indexer cache.Indexer
}

// NewCustomSecretLister returns a new CustomSecretLister.
func NewCustomSecretLister(indexer cache.Indexer) CustomSecretLister {
	return &customSecretLister{indexer: indexer}
}

// List lists all CustomSecrets in the indexer.
func (s *customSecretLister) List(selector labels.Selector) (ret []*v1alpha1.CustomSecret, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CustomSecret))
	})
	return ret, err
}

// CustomSecrets returns an object that can list and get CustomSecrets.
func (s *customSecretLister) CustomSecrets(namespace string) CustomSecretNamespaceLister {
	return customSecretNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CustomSecretNamespaceLister helps list and get CustomSecrets.
// All objects returned here must be treated as read-only.
type CustomSecretNamespaceLister interface {
	// List lists all CustomSecrets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.CustomSecret, err error)
	// Get retrieves the CustomSecret from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.CustomSecret, error)
	CustomSecretNamespaceListerExpansion
}

// customSecretNamespaceLister implements the CustomSecretNamespaceLister
// interface.
type customSecretNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CustomSecrets in the indexer for a given namespace.
func (s customSecretNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.CustomSecret, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CustomSecret))
	})
	return ret, err
}

// Get retrieves the CustomSecret from the indexer for a given namespace and name.
func (s customSecretNamespaceLister) Get(name string) (*v1alpha1.CustomSecret, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("customsecret"), name)
	}
	return obj.(*v1alpha1.CustomSecret), nil
}
