// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CustomConfigMapListerExpansion allows custom methods to be added to
// CustomConfigMapLister.
type CustomConfigMapListerExpansion interface{}

// CustomConfigMapNamespaceListerExpansion allows custom methods to be added to
// CustomConfigMapNamespaceLister.
type CustomConfigMapNamespaceListerExpansion interface{}

// CustomSecretListerExpansion allows custom methods to be added to
// CustomSecretLister.
type CustomSecretListerExpansion interface{}

// CustomSecretNamespaceListerExpansion allows custom methods to be added to
// CustomSecretNamespaceLister.
type CustomSecretNamespaceListerExpansion interface{}
