// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	configuratorcontrollerv1alpha1 "github.com/gopaddle-io/configurator/pkg/apis/configuratorcontroller/v1alpha1"
	versioned "github.com/gopaddle-io/configurator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/gopaddle-io/configurator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/gopaddle-io/configurator/pkg/client/listers/configuratorcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CustomSecretInformer provides access to a shared informer and lister for
// CustomSecrets.
type CustomSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CustomSecretLister
}

type customSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCustomSecretInformer constructs a new informer for CustomSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomSecretInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCustomSecretInformer constructs a new informer for CustomSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfiguratorV1alpha1().CustomSecrets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfiguratorV1alpha1().CustomSecrets(namespace).Watch(context.TODO(), options)
			},
		},
		&configuratorcontrollerv1alpha1.CustomSecret{},
		resyncPeriod,
		indexers,
	)
}

func (f *customSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomSecretInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customSecretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&configuratorcontrollerv1alpha1.CustomSecret{}, f.defaultInformer)
}

func (f *customSecretInformer) Lister() v1alpha1.CustomSecretLister {
	return v1alpha1.NewCustomSecretLister(f.Informer().GetIndexer())
}
