// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/gopaddle-io/configurator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CustomConfigMaps returns a CustomConfigMapInformer.
	CustomConfigMaps() CustomConfigMapInformer
	// CustomSecrets returns a CustomSecretInformer.
	CustomSecrets() CustomSecretInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CustomConfigMaps returns a CustomConfigMapInformer.
func (v *version) CustomConfigMaps() CustomConfigMapInformer {
	return &customConfigMapInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CustomSecrets returns a CustomSecretInformer.
func (v *version) CustomSecrets() CustomSecretInformer {
	return &customSecretInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
