apiVersion: "configurator.gopaddle.io/v1alpha1"
kind: CustomSecret
metadata:
 name: secrettest
 namespace: test
spec:
  secretName: testsecret
  type: bootstrap.kubernetes.io/token
  stringData:
    auth-extra-groups: "system:bootstrappers:kubeadm:default-node-token"
    expiration: "2020-09-13T04:39:10Z"
    token-id: "5emitj"
    token-secret: "kq4gihvszzgn1p0r"
    usage-bootstrap-authentication: "true"
    usage-bootstrap-signing: "true"
  secretAnnotations:
    name: "sa-name"